"""
Part 2 - Simulated Classroom (HLD 6.1, 6.5).

Converts a VerifiedKnowledgeRecord into a turn-by-turn dialogue between
teacher / basic_student / advanced_student, with hints (hidden reveal) and
fill-in-the-blank turns inserted at intuition-testable points, plus a
teach-back turn at the end (interaction modality escalation: read -> type ->
speak, HLD 6.5).

The turn *structure* (which persona speaks when, hint vs. blank placement,
Bloom-level progression) is fixed — that sequence encodes the pedagogical
design from the HLD and shouldn't vary per concept. What varies is the
*content*: in live mode, each turn is generated by an LLM grounded in the
verified explanation, built up sequentially so later turns (e.g. the blank)
can reference what an earlier turn (e.g. the advanced student's worked
situation) actually said. In mock mode, or if no provider is configured,
falls back to fixed templates so the pipeline still works with zero API
keys — same fallback pattern as the verification engine.

`build_dialogue` returns a plain list of turn dicts so it's easy to test /
swap out. The streaming (SSE) happens in routers/classroom.py, which
iterates this list with a small delay to simulate turn-by-turn arrival —
that's a presentation-layer pacing choice, independent of how the content
was generated.
"""
from app.config import settings
from app.content.loader import get_concept
from app.models import VerifiedKnowledgeRecord
from app.services.llm_providers import generate, preferred_available_provider


def _turn_specs(name: str) -> list[dict]:
    return [
        {
            "speaker": "teacher",
            "turn_type": "dialogue",
            "target_bloom_level": "remember",
            "mock_content": None,  # filled in by caller using verified_text
            "live_prompt": lambda transcript, name=name: (
                f"You are a teacher introducing the concept '{name}' to a first-year "
                f"engineering student for the first time. Ground your explanation in "
                f"this verified material:\n\n{transcript}\n\n"
                f"Write your opening explanation — 2-3 sentences, precise, no preamble "
                f"like 'Sure' or 'Great question'. Just the explanation."
            ),
        },
        {
            "speaker": "basic_student",
            "turn_type": "dialogue",
            "target_bloom_level": "understand",
            "mock_content": f"Wait — can you say that in plain words? What does '{name}' actually mean day to day?",
            "live_prompt": lambda transcript, name=name: (
                f"You are a first-year student who learns best in plain, everyday words "
                f"and isn't afraid to ask the class to slow down. So far in class:\n\n{transcript}\n\n"
                f"Ask the teacher to restate '{name}' more simply. One or two sentences, "
                f"natural spoken voice, no meta-commentary like 'As a student I would say'."
            ),
        },
        {
            "speaker": "teacher",
            "turn_type": "hint",
            "target_bloom_level": "understand",
            "mock_content": "Before I answer: what do *you* think happens here? (Hint hidden until you guess.)",
            "live_prompt": lambda transcript, name=name: (
                f"So far in class:\n\n{transcript}\n\n"
                f"As the teacher, before restating '{name}' more simply, turn it back to the "
                f"class with one short encouraging prompt asking them to guess first. Don't "
                f"give away the answer. One sentence."
            ),
        },
        {
            "speaker": "advanced_student",
            "turn_type": "dialogue",
            "target_bloom_level": "apply",
            "mock_content": f"Here's a worked situation involving {name}. Let's apply it.",
            "live_prompt": lambda transcript, name=name: (
                f"You are a stronger student who wants to apply concepts to concrete "
                f"situations. So far in class:\n\n{transcript}\n\n"
                f"Propose ONE specific, concrete situation where '{name}' applies, and say "
                f"you want to work through it. 1-2 sentences."
            ),
        },
        {
            "speaker": "teacher",
            "turn_type": "blank",
            "target_bloom_level": "apply",
            "mock_content": "Fill in the blank: in this situation, the key quantity is ____.",
            "live_prompt": lambda transcript, name=name: (
                f"So far in class:\n\n{transcript}\n\n"
                f"As the teacher, write ONE fill-in-the-blank question testing whether the "
                f"student can apply '{name}' to the situation the advanced student just "
                f"proposed. End the sentence with '____'. One sentence only, no explanation "
                f"of the answer."
            ),
        },
        {
            "speaker": "advanced_student",
            "turn_type": "dialogue",
            "target_bloom_level": "analyse",
            "mock_content": f"Now a boundary case — what if the usual assumption behind {name} breaks down?",
            "live_prompt": lambda transcript, name=name: (
                f"So far in class:\n\n{transcript}\n\n"
                f"As the advanced student, push into a boundary or edge case where the usual "
                f"assumption behind '{name}' might break down. Phrase it as a question to the "
                f"class. 1-2 sentences."
            ),
        },
        {
            "speaker": "teacher",
            "turn_type": "dialogue",
            "target_bloom_level": "apply",
            "mock_content": "Good. Now, in your own words, explain this back to me — type it, or use voice.",
            "live_prompt": lambda transcript, name=name: (
                f"So far in class:\n\n{transcript}\n\n"
                f"As the teacher, wrap up this part of the lesson and ask the student to "
                f"explain '{name}' back in their own words, typed or spoken. One warm, "
                f"encouraging sentence."
            ),
        },
    ]


async def build_dialogue(record: VerifiedKnowledgeRecord) -> list[dict]:
    concept = get_concept(record.concept_id)
    name = concept["name"] if concept else (record.topic_name or record.concept_id)
    specs = _turn_specs(name)
    # the first turn's mock content depends on verified_text, fill it in now
    specs[0]["mock_content"] = f"Let's look at {name}. {record.verified_text}"

    if settings.llm_mode != "live":
        return [_finalize(spec, spec["mock_content"]) for spec in specs]

    provider = preferred_available_provider()
    if not provider:
        return [_finalize(spec, spec["mock_content"]) for spec in specs]

    turns = []
    transcript = f"Verified explanation of '{name}': {record.verified_text}\n\n"
    for spec in specs:
        try:
            content = (await generate(provider, spec["live_prompt"](transcript), concept_name=name)).strip()
            if not content:
                content = spec["mock_content"]
        except Exception:
            # one turn failing to generate shouldn't take down the whole
            # lesson — drop back to the template for just this turn
            content = spec["mock_content"]
        turns.append(_finalize(spec, content))
        transcript += f"{spec['speaker']}: {content}\n"
    return turns


def _finalize(spec: dict, content: str) -> dict:
    return {
        "speaker": spec["speaker"],
        "turn_type": spec["turn_type"],
        "content": content,
        "target_bloom_level": spec["target_bloom_level"],
    }


async def insert_learner_question(question_text: str, verified_text: str, concept_name: str) -> dict:
    """
    Learner enters as third student (HLD 6.1). In live mode, the answer is
    grounded in verified_text via an LLM call; in mock mode, falls back to
    truncating the verified text, same as before.
    """
    if settings.llm_mode == "live":
        provider = preferred_available_provider()
        if provider:
            prompt = (
                f"You are a teacher. A student just asked: '{question_text}' about the "
                f"concept '{concept_name}'. Answer it directly, grounded in this verified "
                f"material:\n\n{verified_text}\n\n"
                f"2-3 sentences, no preamble."
            )
            try:
                content = (await generate(provider, prompt, concept_name=concept_name)).strip()
                if content:
                    return {"speaker": "teacher", "turn_type": "dialogue", "content": content, "target_bloom_level": None}
            except Exception:
                pass  # fall through to the mock-style answer below

    return {
        "speaker": "teacher",
        "turn_type": "dialogue",
        "content": f"Good question. In context: {verified_text[:200]}...",
        "target_bloom_level": None,
    }
